package com.nexora.ticket.workflow;

/** Inputs and preconditions that a later workflow service must validate. */
public enum TicketTransitionRequirement {
    VALID_CATEGORY_AND_PUBLISHED_FORM,
    VALID_LOCATION,
    ASSET_POLICY_SATISFIED,
    VALID_DYNAMIC_FIELD_VALUES,
    REQUIRED_EVIDENCE_PRESENT,
    ASSIGNEE,
    ASSIGNEE_ELIGIBLE_OR_APPROVED_OVERRIDE,
    NON_BLANK_OVERRIDE_REASON_WHEN_OVERRIDDEN,
    RESOLUTION_OUTCOME,
    NON_BLANK_RESOLUTION_SUMMARY,
    EXISTING_WORK_LOG
}
