export const DYNAMIC_FIELD_TYPE_CODES = Object.freeze({
  TEXT: 'TEXT',
  TEXTAREA: 'TEXTAREA',
  NUMBER: 'NUMBER',
  SELECT: 'SELECT',
  MULTI_SELECT: 'MULTI_SELECT',
  DATE: 'DATE',
  DATETIME: 'DATETIME',
  BOOLEAN: 'BOOLEAN',
  IMAGE: 'IMAGE',
})

export const DYNAMIC_FIELD_TYPES = Object.freeze(
  Object.values(DYNAMIC_FIELD_TYPE_CODES),
)

export const DYNAMIC_FIELD_TYPE_LABELS = Object.freeze({
  [DYNAMIC_FIELD_TYPE_CODES.TEXT]: 'Text',
  [DYNAMIC_FIELD_TYPE_CODES.TEXTAREA]: 'Long text',
  [DYNAMIC_FIELD_TYPE_CODES.NUMBER]: 'Number',
  [DYNAMIC_FIELD_TYPE_CODES.SELECT]: 'Select',
  [DYNAMIC_FIELD_TYPE_CODES.MULTI_SELECT]: 'Multi-select',
  [DYNAMIC_FIELD_TYPE_CODES.DATE]: 'Date',
  [DYNAMIC_FIELD_TYPE_CODES.DATETIME]: 'Date and time',
  [DYNAMIC_FIELD_TYPE_CODES.BOOLEAN]: 'Yes/No',
  [DYNAMIC_FIELD_TYPE_CODES.IMAGE]: 'Image',
})
